cosmicpython/book

chapter_01_domain_model.asciidoc, chapter_02_repository.asciidoc, mypy.ini
found this trailing on the `value-objects` branch.
=> Repository pattern desc

.gitignore, Makefile, chapter_01_domain_model.asciidoc, chapter_03_flask_api_and_service_layer.asciidoc, chapter_04_uow.asciidoc, chapter_05_aggregate.asciidoc, chapter_06_events_and_message_bus.asciidoc, chapters.py, checkout-branches-for-ci.py, fix-branches.py, push-branches.py, tests.py
=> Services primitives

chapter_02_repository.asciidoc, chapter_03_service_layer.asciidoc, chapter_04_uow.asciidoc, chapter_05_aggregate.asciidoc, chapter_06_events_and_message_bus.asciidoc, chapter_07_external_events.asciidoc, mypy.ini
this is actually turning out quite good i think
=> Go all in on Abstract Base Classes

acknowledgements.asciidoc
=> Fix Gil's name

chapter_05_aggregate.asciidoc
based on @abdullahariff feedback
=> Try to split out explanation of aggregates into conceptual vs data-integrity/concurrency

chapter_02B_abstractions.asciidoc
1. Almost now logic -> almost "no" logic
2. source_/dest_ hashes -> src_/dst_ hashes to match the rest of the function
=> Minor fixes for "A Brief Interlude: On Coupling and Abstractions"

appendix_django.asciidoc, chapter_01_domain_model.asciidoc, chapter_02_repository.asciidoc, chapter_03_service_layer.asciidoc, chapter_04_uow.asciidoc, chapter_06_events_and_message_bus.asciidoc, chapter_07_external_events.asciidoc, chapter_09_cqrs.asciidoc, chapter_10_dependency_injection.asciidoc, rebase-chapters.sh
fix #27 , also a todo from #43
=> Moderately entertaining skus

chapter_02B_abstractions.asciidoc
Trying something different for leaving comments this time with a PR.
This is not really merge-able because of the edits to the code blocks, but I could break it into smaller PRs that match accepted issues.
=> Chapter 02b comments

chapter_02_repository.asciidoc, chapter_04_service_layer.asciidoc, chapter_05_uow.asciidoc, chapter_06_aggregate.asciidoc, chapter_07_events_and_message_bus.asciidoc, chapter_08_all_messagebus.asciidoc
maybe will also help to address the question from #21
=> Talk about trade-offs at the end of each chapter. What did we get, and what did it cost?

chapter_03_abstractions.asciidoc
=> try to address an EJ todo

Readme.md
Thought I had a mini-stroke clicking on Chapter 10 and getting Chapter 8 instead. Turns out Im just fine and the link was a little off. Fixed it for you
=> Fixed broken Chapter 10 link + test badge

chapter_06_aggregate.asciidoc
=> Ch5 Update for grammar

chapter_04_service_layer.asciidoc
The number of tests is per the paragraph below.
Love the book by the way! It could not have come at a better time for me.
=> fixed to show proper api test amount

chapter_08_all_messagebus.asciidoc
Sorry if I keep making separate pull requests. I’m not totally sure how to merge them together or if that is what you’d want. 
I’m extremely appreciative of the work put into this book!
=> Typo chapter 8

chapter_08_all_messagebus.asciidoc
I think I made the intent clearer.
=> Chapter 8 update to clarify point

chapter_01_domain_model.asciidoc, chapter_02_repository.asciidoc, chapter_03_abstractions.asciidoc, chapter_04_service_layer.asciidoc, chapter_05_uow.asciidoc, chapter_07_events_and_message_bus.asciidoc, chapter_08_all_messagebus.asciidoc, chapter_09_commands.asciidoc
Fixed a couple of typos and added some comments.
I did review an earlier version of the book (3247421cf63db5b73ca6fe45646e34a488a672b8) and I do hope that I have updated all my comments to the current version.
=> Added some comments, minor corrections

chapter_05_uow.asciidoc
Looks like at some point a factory function was being injected instead of the uow?
=> replace uow_start with uow in example

appendix_bootstrap.asciidoc, appendix_django.asciidoc, appendix_project_structure.asciidoc, chapter_04_service_layer.asciidoc, chapter_05_uow.asciidoc, chapter_06_aggregate.asciidoc, chapter_07_events_and_message_bus.asciidoc, chapter_08_all_messagebus.asciidoc, chapter_09_commands.asciidoc, chapter_10_external_events.asciidoc, chapter_11_cqrs.asciidoc, chapter_12_dependency_injection.asciidoc, tests.py
introduce more subfolders starting in service-layer chapter, cf #64
=> Start introducing nested folder structure (fix #64)

chapter_11_cqrs.asciidoc
* Added a blurb about P/R/G vs Async Post.  The reference to P/R/G was a bit confusing since there is actually no re-direct shown in the snippets.  Async Post should also be more widely known, since P/R/G specifically addresses a problem with a human user and a browser.
* Comments/nitpicks about HTTP API details.  Might be a PITA to change at this point, but it will help the reader understanding the examples.
=> comments on async post, RESTful API style

appendix_validation.asciidoc, chapter_02_repository.asciidoc, chapter_03_abstractions.asciidoc, chapter_04_service_layer.asciidoc, chapter_05_uow.asciidoc, chapter_06_aggregate.asciidoc
=> Comments from Hynek in Part 1

Makefile, chapter_01_domain_model.asciidoc, chapter_02_repository.asciidoc, chapter_03_abstractions.asciidoc, chapter_04_service_layer.asciidoc, chapter_05_uow.asciidoc, chapter_06_aggregate.asciidoc
For part 1:
EJ1 -> should/must fix
EJ2 -> nice-to-have
EJ3 -> minor
Will follow up with part 2.
=> Part1 todo rank ej

chapter_04_service_layer.asciidoc
Fixes some weird things with alignment/text not showing up in the rendered png.
=> fixed ch4 test spectrum diagram

chapter_12_cqrs.asciidoc, epilogue_1_how_to_get_there_from_here.asciidoc
@hjwp - I don't know what to say about this one.
I do think @hynek makes a good point re: SqlAlchemy Core. While I wouldn't _always_ use it, it's certainly a good first step to separating a read model using the same technology choices as the rest of the app.
=> Remove references to craziness, insanity, etc.

chapter_09_all_messagebus.asciidoc, chapter_11_external_events.asciidoc, chapter_12_cqrs.asciidoc, chapter_13_dependency_injection.asciidoc
=> Part2 reader exercises

epilogue_1_how_to_get_there_from_here.asciidoc
=> Update our blurb on working with multiple aggregates 

chapter_05_high_gear_low_gear.asciidoc, chapter_06_uow.asciidoc, chapter_07_aggregate.asciidoc, chapter_09_all_messagebus.asciidoc, chapter_13_dependency_injection.asciidoc, preface.asciidoc
=> A few more tweaks suggested by Brandon.

part1.asciidoc
The current sentence is nonsensical. I've guessed an appropriate replacement, that could achieve what may have been your intent.
=> Replace misplaced word

chapter_01_domain_model.asciidoc, chapter_04_service_layer.asciidoc, preface.asciidoc
fixes #267 
no real difference in pdfs as rendered.
=> get rid of all the ugly passthru xrefs

appendix_django.asciidoc, chapter_01_domain_model.asciidoc, chapter_04_service_layer.asciidoc, chapter_06_uow.asciidoc, chapter_09_all_messagebus.asciidoc, chapter_11_external_events.asciidoc, chapter_12_cqrs.asciidoc, introduction.asciidoc
=> some terminology find+replaces 

appendix_csvs.asciidoc, appendix_django.asciidoc, appendix_ds1_table.asciidoc, appendix_project_structure.asciidoc, appendix_validation.asciidoc, chapter_01_domain_model.asciidoc, chapter_02_repository.asciidoc, chapter_03_abstractions.asciidoc, chapter_04_service_layer.asciidoc, chapter_05_high_gear_low_gear.asciidoc, chapter_06_uow.asciidoc, chapter_07_aggregate.asciidoc, chapter_08_events_and_message_bus.asciidoc, chapter_09_all_messagebus.asciidoc, chapter_10_commands.asciidoc, chapter_11_external_events.asciidoc, chapter_12_cqrs.asciidoc, chapter_13_dependency_injection.asciidoc
currently working off the atlas branch to be able to pdfdiff, will need merge.
=> tidy up indexing markup

chapter_07_aggregate.asciidoc
I can't figure out how to create shorted URL using https://oreil.ly, so I linked directly to Github.
=> fix git branch text for chapter 07

appendix_validation.asciidoc
line 372, we have `def product_exists(event, uow)`
=> Appendix validation - update args order in example

chapter_03_abstractions.asciidoc
The function name is "sync", not "synchronise_dirs"
=> Fix wrong function name

chapter_04_service_layer.asciidoc
Thanks for making the book available in this format!
This pull request just contains a small fix for variable naming
=> Fix typo in e2e test code in chapter 4

epilogue_1_how_to_get_there_from_here.asciidoc
=> Fix url for Event Storming

chapter_01_domain_model.asciidoc
the comment talks about type hints
=> Fix code comment location

part1.asciidoc
Fixed "the proof is in the pudding" to "the proof of the pudding". The phrase is: "The proof of the pudding is in the eating." That's how you know it's pudding. If the proof would be in the pudding, it would just be messy.
=> Pudding should now be less messy
